### ISSUE TITLE
Fixed Media\Settings menu crashes on most options

### ISSUE THREAD

**Issue by dark-c0de** [ElDewrito/DewRecode#25]
I see you've "fixed" displaying the Media\Settings menu. Are any of these settings really needed? It seems like most of the options available just crash the game.

**Comment by emoose** [comment]
What crashes it for you? I only get crashes when trying to edit the service tag (which is probably because it tries opening a VirtualKeyboard, and VK isn't complete in DR yet afaik)

It's probably not really needed, but being able to access it could be helpful: eg. the appearance menu lets you change between male/female, and I remember people in dev chan wondering how it's done, so now we can see how.
